### ISSUE TITLE
Make it available on Docker Hub

### ISSUE THREAD

**Issue by kaloyan-raev** [janatzend/docker-php7-nightly-build#5]
I hope this be published to [Docker Hub](https://hub.docker.com/), so it can just be pulled easily as an image instead of cloning and building the Git repo.

**Comment by janatzend** [comment]
The nature of this repo is the ability to build a new image every day with the most current PHP 7. 
The only option I see to publish it on Docker Hub is to use the Automated Build system of Docker (https://docs.docker.com/docker-hub/builds/). However, a new build still has to be invoked manually if there are no changes in the repo. This manual step could be automated, so that a new build is triggered every night - maybe with IFTTT ? Not sure about it... Other ideas?

**Comment by kaloyan-raev** [comment]
I am not aware of IFTTT. I imagine that a simple cron job can trigger the automated build remotely as described in the "Remote Build triggers" section of the page you've linked.

There free online services for cron job. https://cron-job.org is one example.

**Comment by janatzend** [comment]
Here you go:
https://hub.docker.com/r/janatzend/docker-php7-nightly-build/

Let's wait until tomorrow 5am whether cron-job.org does the job and updates the image! Thanks for the tip ;-)

**Comment by kaloyan-raev** [comment]
Thanks! Waiting for the build.

**Comment by janatzend** [comment]
ok, seems to work :)

FYI: Instead of https://cron-job.org I had to use http://crondash.com as cron-job.org doesn't support POST requests.
